require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ActivationsController do

  def mock_activation(stubs={})
    @mock_activation ||= mock_model(Activation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all activations as @activations" do
      Activation.stub(:all) { [mock_activation] }
      get :index
      assigns(:activations).should eq([mock_activation])
    end
  end

  describe "GET show" do
    it "assigns the requested activation as @activation" do
      Activation.stub(:find).with("37") { mock_activation }
      get :show, :id => "37"
      assigns(:activation).should be(mock_activation)
    end
  end

  describe "GET new" do
    it "assigns a new activation as @activation" do
      Activation.stub(:new) { mock_activation }
      get :new
      assigns(:activation).should be(mock_activation)
    end
  end

  describe "GET edit" do
    it "assigns the requested activation as @activation" do
      Activation.stub(:find).with("37") { mock_activation }
      get :edit, :id => "37"
      assigns(:activation).should be(mock_activation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created activation as @activation" do
        Activation.stub(:new).with({'these' => 'params'}) { mock_activation(:save => true) }
        post :create, :activation => {'these' => 'params'}
        assigns(:activation).should be(mock_activation)
      end

      it "redirects to the created activation" do
        Activation.stub(:new) { mock_activation(:save => true) }
        post :create, :activation => {}
        response.should redirect_to(activation_url(mock_activation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved activation as @activation" do
        Activation.stub(:new).with({'these' => 'params'}) { mock_activation(:save => false) }
        post :create, :activation => {'these' => 'params'}
        assigns(:activation).should be(mock_activation)
      end

      it "re-renders the 'new' template" do
        Activation.stub(:new) { mock_activation(:save => false) }
        post :create, :activation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested activation" do
        Activation.stub(:find).with("37") { mock_activation }
        mock_activation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :activation => {'these' => 'params'}
      end

      it "assigns the requested activation as @activation" do
        Activation.stub(:find) { mock_activation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:activation).should be(mock_activation)
      end

      it "redirects to the activation" do
        Activation.stub(:find) { mock_activation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(activation_url(mock_activation))
      end
    end

    describe "with invalid params" do
      it "assigns the activation as @activation" do
        Activation.stub(:find) { mock_activation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:activation).should be(mock_activation)
      end

      it "re-renders the 'edit' template" do
        Activation.stub(:find) { mock_activation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested activation" do
      Activation.stub(:find).with("37") { mock_activation }
      mock_activation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the activations list" do
      Activation.stub(:find) { mock_activation }
      delete :destroy, :id => "1"
      response.should redirect_to(activations_url)
    end
  end

end
